ant	hormiga
antelope	antilope
beaver	castor
bedbug	chinche
bee	abeja
bison	bisonte
bull	toro
butterfly	mariposa
calf	ternero
camel	camello
carp	carpa
cat	gato
chamois	gamuza
chicken	pollo
ock	gallo
cockroach	cucaracha
crane	grulla
crayfish	cangrejo
crocodile	cocodrilo
deer	ciervo
dog	perro
donkey	burro
dove	paloma
elephant	elefante
fly	mosca
foal	potro
fox	zorro
frog	rana
giraffe	jirafa
gnat	mosquito
goat	cabra
goose	oca
gorilla	gorila
guinea	cobaya
gull	gaviota
hawk	alferraz
hedgehog	erizo
hen	gallina
herring	arenque
horse	caballo
hummingbird	colibri
hyena	hiena
jackal	chacal
jaguar	jaguar
jellyfish	medusa
kangaroo	canguro
kid	cabrito
lizard	lagarto
lobster	bogavante
locust	langosta
louse	piojo
lynx	lince
mare	yegua
mole	topo
ostrich	avestruz
otter	nutria
owl	buho
oyster	ostra
pandabear	panda
panther	pantera
parrot	loro
pig	cerdo
piglet	cochinillo
pike	lucio
polarbear	osopolar
pony	poni
rabbit	conejo
raccoon	mapache
rat	rata
raven	cuervo
rayfish	raya
rhinoceros	rinoceronte
roe	corzo
seal	foca
shark	tibur
sheep	oveja
skylark	alondra
sloth	perezoso
snail	caracol
snake	serpiente
squid	calamar
squirrel	ardilla
stagbeetle	ciervovolante
starling	estornino
swallow	golondrina
swan	cisne
tadpole	renacuajo
tick	garrapata
tiger	tigre
trout	trucha
turtle	tortuga
wasp	avispa
whale	ballena
wolf	lobo
zebra	cebra
blouse	blusa
boots	botas
cap	gorro
clothes	ropa
coat	abrigo
flannel	franela
glove	guantes
gown	bata
hat	sombrero
jacket	chaqueta
leather	cuero
necktie	corbata
pajamas	pijama
pocket	bolsillo
raincoat	impermeable
scarf	bufanda
shirt	camisa
shoes	zapatos
silk	seda
skirt	falda
sleeve	manga
slippers	zapatillas
suit	traje
sunglasses	gafasdesol
tuxedo	esmoquin
velvet	terciopelo
vest	chaleco
wool	lana
zipper	cremallera
beer	cerveza
biscuit	galleta
brandy	aguardiente
bratwurst	salchicha
bread	pan
bun	panecillo
butter	mantequilla
cake	bollo
can	conserva
cheese	queso
chocolate	chocolate
cider	sidra
cinnamon	canela
cocoa	cacao
ream	nata
egg	huevo
fish	pescado
flour	harina
honey	miel
icecream	helado
juice	zumo
margarine	margarina
meat	carne
milk	leche
mineralwater	aguamineral
mustard	mostaza
oliveoil	aceitedeoliva
pepper	pimienta
raisin	uvapasa
rice	arroz
sausage	chorizo
softdrink	refresco
spice	especia
inegar	vinagre
water	agua
wine	vino
yoghurt	yogurt
affiliatecompany	filial
assortment	surtido
auction	subasta
balance	saldo
bank	banco
bankruptcy	quiebra
business	negocio
capital	capital
client	cliente
company	empresa
competition	competencia
consumer	consumidor
consumption	consumo
customs	aduana
debt	deuda
demand	demanda
expenses	gastos
exporter	exportador
fair	feria
finances	finanzas
foreignexchange	divisa
goods	bienes
importer	importador
industry	industria
insurance	seguro
investment	ingreso
invoice	factura
market	mercado
money	dinero
order	pedido
price	precio
profit	lucro
resources	recursos
shareholder	accionista
store	tienda
stockexchange	bolsa
supply	oferta
tax	impuesto
trade	comercio
unemployment	desempleo

<script type="text/javascript">
top.location="index.php";
</script>
